CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    age INT NOT NULL,
    email VARCHAR (200) NOT NULL,
    password VARCHAR (200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;